blank_issues_enabled: true
contact_links:
  - name: 💬 Ask on Github Discussions
    url: https://github.com/skarllot/flow-pair/discussions
    about: The best place for asking general purpose questions.
